Repository massalabs/as, pull requests merged in 2023-05, with the labels that each got.

#155 Set _m in the binomial class
  README.md
  packages/as-proba/assembly/probability/binomial.ts
Labels: documentation

#242 Fix: dependencies importing in protobuf transformer
  packages/as-transformer/src/helpers/protobuf.ts
  packages/as-transformer/src/transformer.ts
  packages/as-transformer/src/transformers/massaExport.ts
  packages/as-transformer/tests/transformers/massaExports.ts
Labels: bug

#220 Chore: updated dependencies
  package-lock.json
  packages/as-proba/package.json
  packages/as-transformer/package.json
  packages/as-types/package.json
Labels: On Hold, dependencies

#255 Feature(as-transformer): added an MassaExport calls transformer
  packages/as-transformer/src/transformer.ts
  packages/as-transformer/src/transformers/interfaces/Update.ts
  packages/as-transformer/src/transformers/massaExport.ts
  packages/as-transformer/src/transformers/massaExportCalls.ts
Labels: bug
